FROM odoo:17.0
# Menyalin file dengan kepemilikan root
COPY --chown=root:root ./config /etc/odoo
COPY --chown=root:root ./addons /mnt/extra-addons
COPY --chown=root:root ./entrypoint.sh /entrypoint.sh
# Menetapkan pengguna root untuk menjalankan perintah
USER root
# Mengubah izin file
RUN chmod +x /entrypoint.sh
RUN chown odoo /etc/odoo/odoo.conf \
    && mkdir -p /mnt/extra-addons \
    && chown -R odoo /mnt/extra-addons
USER odoo
VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]
EXPOSE 8069 8071 8072
ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]