apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: kube-bestindo
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: odoo
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'chmod -R 777 /var/lib/odoo/sessions /var/lib/odoo/filestore']
        volumeMounts:
        - name: odoo-sessions-pvc
          mountPath: /var/lib/odoo/sessions
        - name: odoo-filestore-pvc
          mountPath: /var/lib/odoo/filestore
      containers:
      - name: odoo
        image: venziuno/master:latest
        env:
          - name: HOST
            value: 103.160.95.134  # PostgreSQL host
          - name: USER
            value: odoo17
          - name: PASSWORD
            value: odoo17
        volumeMounts:
        - name: odoo-filestore-pvc
          mountPath: /var/lib/odoo/filestore
        - name: odoo-sessions-pvc
          mountPath: /var/lib/odoo/sessions
      volumes:
      - name: odoo-filestore-pvc
        persistentVolumeClaim:
          claimName: odoo-filestore-pvc
      - name: odoo-sessions-pvc
        persistentVolumeClaim:
          claimName: odoo-sessions-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-sessions-pvc
  namespace: kube-bestindo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore-pvc
  namespace: kube-bestindo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sessions
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/odoo-sessions/
  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filestore
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/odoo-filestore/
  storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: kube-bestindo
spec:
  selector:
    app: odoo
  ports:
  - name: http
    port: 8069
    targetPort: 8069
  type: NodePort