from . import res_company
from . import res_partner
from . import res_users
from . import product
from . import bp_promotion
from . import bp_member_point
from . import bp_deposit
from . import multi_location
from . import payment_provider
from . import sale_order
from . import stock_picking
from . import bp_users_roles
from . import account_move
from . import bp_negotiation
from . import delivery_carrier
from . import bp_auth
from . import bp_term
from . import bp_cart