name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: venziuno/autodeploy-odoo17
  NAMESPACES: bestindo
  DEPLOYMENT_NAME: odoo17
  CONTAINER_NAME: odoo17

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Login to Docker registry - VENZIUNO
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.VENZIUNO_USERNAME }}
        password: ${{ secrets.VENZIUNO_PASSWORD }}

    - name: Build Docker image
      run: |
        echo "Building Docker image with name: ${{ env.IMAGE_NAME }}"
        docker build -t ${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}:latest

