name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  REPO_NAME: ${{ github.repository }}  # e.g., myorg/myrepo
  IMAGE_NAME: venziuno
  PROJECT_BRANCH: ${{ github.ref_name }}
  NAMESPACES: kube-bestindo
  DEPLOYMENT_NAME: odoo
  CONTAINER_NAME: odoo

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted 

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Venziuno registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.VENZIUNO_USERNAME }}
        password: ${{ secrets.VENZIUNO_PASSWORD }}
    
    - name: Build and push latest
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile.${{ env.PROJECT_BRANCH }}  # Ensure the Dockerfile naming convention matches
        push: true
        tags: docker.io/${{ env.IMAGE_NAME }}/${{ env.PROJECT_BRANCH }}:latest

    - name: Build and push with SHA tag
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile.${{ env.PROJECT_BRANCH }}  # Ensure the Dockerfile naming convention matches
        push: true
        tags: docker.io/${{ env.IMAGE_NAME }}/${{ env.PROJECT_BRANCH }}:${{ github.sha }}

  dev:
    name: Deploy To Dev
    environment:
      name: dev
    runs-on: self-hosted
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Print environment variables
      run: |
        echo "REPO_NAME: $REPO_NAME"
        echo "IMAGE_NAME: $IMAGE_NAME"
        echo "PROJECT_BRANCH: $PROJECT_BRANCH"
        echo "NAMESPACES: $NAMESPACES"
        echo "DEPLOYMENT_NAME: $DEPLOYMENT_NAME"
        echo "CONTAINER_NAME: $CONTAINER_NAME"
        
    - name: Print base64 config data
      run: echo ${{ secrets.K8S_CONFIG_ALPHA }}
      
    - name: Deploy to cluster
      uses: nickgronow/kubectl@master
      with:
        config_data: ${{ secrets.K8S_CONFIG_ALPHA }}  # Ensure this secret is created
        args: set image --record deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=docker.io/${{ env.IMAGE_NAME }}/${{ env.PROJECT_BRANCH }}:${{ github.sha }} -n ${{ env.NAMESPACES }}
