name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: venziuno/autodeploy-odoo17
  NAMESPACES: bestindo
  DEPLOYMENT_NAME: odoo17
  CONTAINER_NAME: odoo17

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker registry - VENZIUNO
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.VENZIUNO_USERNAME }}
        password: ${{ secrets.VENZIUNO_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest


