name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: venziuno/autodeploy-odoo17  # Gets the repo name on GitHub
  PROJECT_BRANCH: ${{ github.ref_name }}  # Gets the branch or tag on GitHub
  NAMESPACES: bestindo
  DEPLOYMENT_NAME: odoo17
  CONTAINER_NAME: odoo17

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Login to Docker registry - VENZIUNO
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.VENZIUNO_USERNAME }}  # Ensure this secret is created
        password: ${{ secrets.VENZIUNO_PASSWORD }}  # Ensure this secret is created
        
    - name: Build Docker image
      run: docker build -t venziuno/${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: docker push venziuno/${{ env.IMAGE_NAME }}:latest
