name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ github.repository }}  # Gets the repo name on GitHub
  PROJECT_BRANCH: ${{ github.ref_name }}  # Gets the branch or tag on GitHub
  NAMESPACES: bestindo
  DEPLOYMENT_NAME: odoo17
  CONTAINER_NAME: odoo17

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker registry - VENZIUNO
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Ensure this secret is created
        password: ${{ secrets.DOCKER_PASSWORD }}  # Ensure this secret is created
        
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.PROJECT_BRANCH }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.PROJECT_BRANCH }}
